name: Update Submodules

on:
  schedule:
    # Run daily at 12:00 AM UTC (cron format: minute hour day month weekday)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update submodules
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Update all submodules to their latest commits
        git submodule update --remote --merge
        
        # Check if there are any changes
        if git diff --quiet; then
          echo "No submodule updates available"
          exit 0
        fi
        
        # Stage and commit changes
        git add .
        git commit -m "Auto-update submodules - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        
        # Push changes
        git push